apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:cloudformation:us-west-2:610952542558:stack/eksctl-simple-jwt-api-nodegroup-ng-d11b1934/1017e440-7c5f-11ea-a949-0a59d9cb58e4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-12T01:48:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "921"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: afead2ec-7c5f-11ea-a87a-0a13265af4ee
env:
  parameter-store:
    JWT_SECRET: JWT_SECRET