apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::610952542558:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::610952542558:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-752H9L4VH0Q3
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-16T19:10:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "816"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ca62db84-b9d1-48c3-9804-c4c918ccfa70