apiVersion: v1
kind: Service
metadata:
  name: eksctl-simple-jwt-api-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 50
      targetPort: 5000
  selector:
    app: eksctl-simple-jwt-api-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksctl-simple-jwt-api-cluster
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: eksctl-simple-jwt-api-cluster
  template:
    metadata:
      labels:
        app: eksctl-simple-jwt-api-cluster
    spec:
      containers:
        - name: eksctl-simple-jwt-api-cluster
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5000
